topk-py/Cargo.toml
topk-rs/Cargo.toml
topk-rs/src/client.rs

* allows SDK to connect to HTTPS endpoints
* fix host from `topk.io`
* bump sdk version

add TLS support

---

.github/workflows/python.yml
topk-py/Cargo.toml

run arm build on arm gha runners

[ci] arm runners

---

topk-js/package.json

topk-js@0.1.19-alpha.3

---

docs/collections/create.mdx
docs/collections/delete.mdx
docs/collections/list.mdx
docs/concepts/consistency.mdx
docs/concepts/semantic-search.mdx
docs/concepts/unified-retrieval.mdx
docs/documents/delete.mdx
docs/documents/query.mdx
docs/documents/upsert.mdx
docs/quickstart.mdx

publishes topk-js docs
fixes some topk python code snippets

topk-js introduction

---

.gitignore
README.md
assets/topk-logo-dark.svg
assets/topk-logo-light.svg
topk-js/README.md
topk-py/README.md

* update package root `README.md`
* updated copy(pls check!!)
* added logo
* removed python only specific copy and added info about multiple SDKs
* removed copy about python development
* removed copy about releases
* add `topk-js/README.md`
* same structure as python
* update `topk-py/README.md`
* added logo

Better readme v1

---

topk-js/index.d.ts
topk-js/src/client/collection.rs
topk-js/src/error.rs
topk-js/tests/documents.spec.ts
topk-js/tests/get.spec.ts
topk-protos/protos/topk/data/v1/query_service.proto
topk-py/src/client/collection.rs
topk-py/src/error.rs
topk-py/tests/test_get.py
topk-rs/src/client/collection.rs
topk-rs/src/error.rs
topk-rs/tests/test_get.rs

to allow multiple to get multiple ids at the same time

change `collection(...).get(id: str)` to `collection(...).get(ids: list[str])`

---

docs/documents/query.mdx

Fixes https://github.com/fafolabs/topk-sdk/issues/29

docs: add contains operator

---

topk-js/index.d.ts
topk-js/src/expr/logical.rs
topk-js/tests/query_logical.spec.ts
topk-py/src/expr/logical.rs
topk-py/tests/test_query_logical.py
topk-rs/src/expr/logical.rs
topk-rs/tests/test_query_logical.rs

Add is null and is not null operators

---

topk-js/package.json
topk-py/Cargo.toml

* Add is_null and is_not_null operators https://github.com/topk-io/topk/pull/68
* `topk-js`: Add better collection error handling https://github.com/topk-io/topk/pull/73
* `topk-js`: Extract match options into an object https://github.com/topk-io/topk/pull/84

Release 0.2.1 SDKs

---

topk-js/Cargo.toml
topk-js/src/error.rs
topk-py/Cargo.toml
topk-py/src/error.rs
topk-rs/src/client/collection.rs
topk-rs/src/error.rs
topk-rs/tests/test_upsert.rs

before, these were wrapped in `CapacityExceeded`

add `SlowDown` and `QuotaExceeded` errors

---

docs/collections/create.mdx
docs/concepts/consistency.mdx
docs/concepts/keyword-search.mdx
docs/concepts/multi-tenancy.mdx
docs/concepts/multi-vector-search.mdx
docs/concepts/reranking.mdx
docs/concepts/semantic-search.mdx
docs/concepts/true-hybrid-search.mdx
docs/concepts/vector-search.mdx
docs/documents/query.mdx
docs/documents/upsert.mdx
docs/quickstart.mdx
topk-py/README.md

* fix invalid python import statement in `upsert.mdx` docs
* add trailing commas where missing
* remove unused imports
* make imports order the same

docs: fix code examples syntax and imports

---

.github/workflows/publish.yml
.github/workflows/publish_js.yml
.github/workflows/publish_python.yml
.github/workflows/publish_test_runner.yml

[ci] publish topk-test-runner:latest

---

.github/workflows/publish.yml

Fixing release pipeline issue: https://github.com/topk-io/topk/actions/runs/16089392760

[ci] fix workflow permission

---

.github/workflows/publish_python.yml
Earthfile

we already pin maturin version [here](https://github.com/topk-io/topk/blob/9c2e6cd1739439572f7a1f74f58f8ac3f163f161/Earthfile#L44C32-L44C32) so pinning in release wfs too to get consistent experience.

[py] pin maturin version

---

Earthfile

allow to override "host" when running e2e tests to shared earthly builders

[ci] earthly host ip override

---

docs/collections/create.mdx
docs/documents/data-constructors.mdx
docs/documents/query.mdx
docs/documents/upsert.mdx

Depends on #184 
* add docs for lists:
* schema constructor `list(valueType)`
* data constuctors
* rephrase data constructors page and update copy here and there

docs: lists

---

Earthfile

https://github.com/topk-io/topk/actions/runs/17078231353/job/48439540675?pr=198#step:4:68

Use python3-venv package

---

topk-js/Cargo.toml
topk-js/package.json
topk-py/Cargo.toml
topk-rs/Cargo.toml

Features latest:
* https://github.com/topk-io/topk/pull/210
* https://github.com/topk-io/topk/pull/212

Release: 0.5.0

---

.github/workflows/workflow_pr.yml
Earthfile

* add a check that verifies that all SDKs are on the same version
* add a check that verifies that the latest `.d.ts` Typescript definition file is being generated and committed to git

feat: Verify SDKs are on the same version and validate latest dts

---

topk-py/docgen/main.py
topk-py/docgen/parse.py
topk-py/docgen/render.py
topk-py/pyproject.toml
topk-py/src/client/async/mod.rs
topk-py/src/client/sync/mod.rs
topk-py/src/data/mod.rs
topk-py/src/expr/logical.rs
topk-py/src/lib.rs
topk-py/src/query/mod.rs
topk-py/src/schema/field_spec.rs
topk-py/src/schema/mod.rs
topk-py/topk_sdk/__init__.pyi
topk-py/topk_sdk/data/__init__.pyi
topk-py/topk_sdk/error/__init__.pyi
topk-py/topk_sdk/query/__init__.pyi
topk-py/topk_sdk/schema/__init__.pyi

* add docstrings to python stub files `*.pyi`
* ~update `topk_sdk/__init__.py` to export all submodules~
* ~remove other submodules `__init__.py`~
* setup docs generation
* remove unused methods `keyword_index()` `vector_index()`
* misc

[topk-py] docstrings and docgen setup

---

topk-js/Cargo.toml
topk-js/package.json
topk-py/Cargo.toml
topk-rs/Cargo.toml

Release 0.6.5
