topk-io/topk

topk-protos/src/data/v1/query_ext.rs
topk-py/src/data/function_expr.rs
topk-py/src/data/query.rs
topk-py/src/data/stage.rs
topk-py/src/query.rs
topk-py/src/schema.rs
topk-py/tests/__init__.py
topk-py/tests/test_collections.py
topk-py/tests/test_documents.py

* add `semantic_index(model: Optional[str] = None)` constructor for defining semantic indexes in collection schema
* add `.rerank(model: Optional[str] = None, query: Optional[str] = None, fields: list[str] = [])` method for creating a `rerank` stage
* add tests exercising these

[py] inference + reranking interfaces

---

.github/workflows/pr.yml
.github/workflows/test.yml
Earthfile
README.md
topk-py/src/client.rs
topk-py/src/schema.rs
topk-py/tests/__init__.py
topk-py/tests/test_collections.py
topk-py/tests/test_documents.py

* adjust python tests to account for dummy embedder/reranked (by not asserting ordering)
* add `earthly --secret TOPK_API_KEY +test-py` entrypoint for easier test running
* add CI for python when PR is labeled with `ready`

improve python tests

---

.github/workflows/pr.yml
Earthfile
topk-rs/Cargo.toml
topk-rs/tests/test_collection.rs
topk-rs/tests/test_delete.rs
topk-rs/tests/test_get.rs
topk-rs/tests/test_query_count.rs
topk-rs/tests/test_query_filter.rs
topk-rs/tests/test_query_logical.rs
topk-rs/tests/test_query_select.rs
topk-rs/tests/test_query_select_union.rs
topk-rs/tests/test_query_text.rs
topk-rs/tests/test_query_unified.rs
topk-rs/tests/test_query_validation.rs
topk-rs/tests/test_query_vector.rs
topk-rs/tests/test_semantic_index.rs
topk-rs/tests/test_upsert.rs
topk-rs/tests/utils/dataset/books.rs
topk-rs/tests/utils/dataset/mod.rs
topk-rs/tests/utils/dataset/semantic.rs
topk-rs/tests/utils/mod.rs
topk-rs/tests/utils/test_context/mod.rs
topk-rs/tests/utils/test_context/project.rs

This PR open-sources our e2e test suite. Also, add `test-rs` earthly target and gh action pipeline

add `topk-rs` tests

---

topk-js/index.d.ts
topk-js/package.json
topk-js/src/query/query.rs
topk-js/tests/semantic_index.spec.ts

Instead of passing rerank arguments like:
```ts
.rerank("dummy", "query string", ["title", "summary"])
```
let's extract them into a struct:
```ts
.rerank({ model: "dummy", query: "query string", fields: ["title", "summary"] })
```
* Also: bump topk-js alpha version

Extract query.rerank() arguments into a struct

---

topk-js/index.d.ts
topk-js/package.json
topk-js/src/schema/mod.rs
topk-js/tests/collections.spec.ts
topk-js/tests/documents.spec.ts
topk-js/tests/query_select.spec.ts
topk-js/tests/query_vector.spec.ts
topk-js/tests/semantic_index.spec.ts

Fixes https://github.com/fafolabs/topk-sdk/issues/42
* pass `options: VectorOptions` struct to `binaryVector(...)`, `f32Vector(...)` and `u8Vector(...)` schema constructors
```typescript
export interface VectorOptions {
dimension: number
}
```
* make `semanticIndex(options?: SemanticIndexOptions | undefined | null)` argument optional
* add typecheck command for typechecking tests

pass struct to vector field constructors | make semantic index arguments optional

---

topk-js/index.d.ts
topk-js/lib/query.d.ts
topk-js/lib/query.js
topk-js/src/query/query.rs
topk-js/tests/query_count.spec.ts
topk-js/tests/query_topk.spec.ts
topk-py/src/query/mod.rs
topk-py/tests/test_delete.py
topk-py/tests/test_query_select.py
topk-py/tests/test_query_validation.py
topk-rs/src/query/mod.rs
topk-rs/tests/test_delete.rs
topk-rs/tests/test_query_select.rs
topk-rs/tests/test_query_validation.rs

It makes sense to let users start queries with `select()` or `filter()`. 
* `top_k()` on its own is not very useful as you'd only get the `_id` field back. forcing user to use `select()` makes it explicit what data is going to be returned
* `client.collection().query(count())` can be written as `client.collection().count()` so no need to export `count()` too

drop `top_k()` and `count()` query builders

---

.github/workflows/js.yml
.github/workflows/python.yml
topk-py/Cargo.toml

Since this is a polyglot repo and we decided that we do not want a "bundled" (all sdks at once) release strategy, I'm removing GH triggers (`on: push: tags`). Each workflow can be dispatched manually from GH UI.
Also bumping python version.

[publish] remove publish on tag

---

topk-js/index.d.ts
topk-js/src/client/collection.rs
topk-js/tests/delete.spec.ts
topk-js/tests/documents.spec.ts
topk-js/tests/upsert.spec.ts
topk-protos/protos/topk/data/v1/query_service.proto
topk-protos/protos/topk/data/v1/write_service.proto
topk-py/src/client/collection.rs
topk-py/tests/test_delete.py
topk-py/tests/test_upsert.py
topk-rs/src/client/collection.rs
topk-rs/tests/test_delete.rs
topk-rs/tests/test_upsert.rs

javascript doesn't have u64s, so `lsn: u64` was problematic. simply encoding this value as str works in all languages (client doesn't manipulate it, just passes along to `query()`/`count()`)

change `lsn` from `u64` to `string`

---

topk-js/package.json
topk-js/src/error.rs
topk-js/tests/collection.spec.ts
topk-js/tests/collections.spec.ts
topk-js/tests/upsert.spec.ts

When playing around with `topk-js` I came across some cryptic `invalid argument` errors while upserting some documents. I was unable to pinpoint the exact validation issue with my documents due to lack of proper error display.
For example, when upserting documents for a schema where my vector had less dimensions than specified in the schema, I got `Error: invalid argument` error instead of `InvalidVectorDimension { doc_id: \"doc1\", field: \"f32_embedding\", expected_dimension: 3, got_dimension: 2 }`
This PR:
* handles all of topk error types and displays additional error info(status, message) if applicable
* adds tests
* bumps alpha version

Better error handling & formatting

---

topk-js/Cargo.toml
topk-js/package.json
topk-js/src/error.rs
topk-py/Cargo.toml
topk-py/src/error.rs
topk-rs/Cargo.toml
topk-rs/src/error.rs

Doing `_ => e.into()` introduces infinite recursion and crashes the client.

add `PermissionDenied` error, fix stack overflow

---

topk-js/Cargo.toml
topk-js/index.d.ts
topk-js/package.json
topk-js/src/client/mod.rs
topk-py/Cargo.toml
topk-py/src/client/mod.rs
topk-rs/Cargo.toml
topk-rs/src/client/collection.rs
topk-rs/src/client/collections.rs
topk-rs/src/client/config.rs
topk-rs/src/client/mod.rs
topk-rs/src/client/retry.rs
topk-rs/src/error.rs
topk-rs/src/lib.rs

Introducing retries baked into `topk-rs` directly (topk-py & topk-js inherit). See the code for default values.
By default we retry in two scenarios:
* server needs client to slow down, `SlowDown` error is returned
* retries are also used for `query(..., lsn=N)` code path

implement retries

---

.github/workflows/publish.yml
.github/workflows/publish_test_runner.yml
Earthfile

Publish `cargo-nextest`-based runner (from topk-rs tests) as image so we can run test in various envs in an encapsulated way.

[tests] publish test runner image

---

Earthfile
topk-js/package.json

The release pipeline passes extra args to `yarn build` which [breaks](https://github.com/topk-io/topk/actions/runs/16002941310/job/45142371021#step:10:176) after I put `&& tsc --noEmit` in the `build` cmd.

[js] fix release pipeline

---

.github/workflows/workflow_pr.yml

Runners `amd64/arm64` were renamed to `public-amd64/public-arm64` in our github org.

[ci] rename github runners

---

.github/workflows/publish.yml
.github/workflows/publish_test_runner.yml

For each release, we publish `topk-test-runner` image that wraps `cargo nextest run -p topk-rs` in a container for easier execution locally/in-cluster/etc.

[ci] publish test runner image

---

protos/topk/data/v1/expr/logical.proto
topk-rs/src/proto/data/v1/query_ext/expr_ext/logical.rs
topk-rs/tests/test_query_hybrid.rs
topk-rs/tests/test_query_logical.rs
topk-rs/tests/utils/dataset/books.rs

Support `coalesce` operator with the following semantics:
```python
def coalesce(x: Array, y: Array):
[x[i] if (x[i] is not None) else y[i] for i in range(len(x))]
```
```bash
PASS [   0.815s] topk-rs::test_query_logical test_query_coalesce_non_nullable
PASS [   0.820s] topk-rs::test_query_logical test_query_coalesce_missing
PASS [   0.825s] topk-rs::test_query_logical test_query_coalesce_nullable
PASS [   0.773s] topk-rs::test_query_hybrid test_query_hybrid_coalesce_score
```

Support null coalescing

---

topk-rs/src/proto/data/v1/query_ext/expr_ext/logical.rs
topk-rs/tests/test_query_hybrid.rs

Add `boost` operator that performs multiplicative boost by `value` based on `condition`. This is effectively the same as `score * cond.choose(value, 1)` expressed in a less verbose way.

boost operator

---

docs/documents/query.mdx

- Added choose, boost, coalesce to Logical
- Added match_all, match_any to Comparison
- Renamed Arithmetic to Mathematical because pow, sqrt etc. will be added in the future
- Moved is_null, is_not_null from Unary to Comparison
- Moved not from Unary to Logical
- Removed Unary category because it doesn't seem meaningful in this context
New categorization:

doc for new ops wip

---

topk-rs/build.rs
topk-rs/src/proto/codec.rs
topk-rs/src/proto/mod.rs
topk-rs/tests/test_client.rs

By default, `prost` will return an INTERNAL_ERROR if the payload cannot be decoded, we want to remap this to INVALID_ARGUMENT instead. 
We limit maximum depth of a `TextExpr` or `LogicalExpr` to 16 (cc @petertoth for docs), but that assume the proto can be decoded by `tonic`. `prost` comes with a baked-in max depth of `100`. There is `no-recursion-limit` feature flag but we don't want since it would be possible to overload the server, only to reject the request right after.
---
This happens, for example, if the proto recursion limit is exceeded (eg. expr to deep). Now, the following error is returned:
```
invalid argument: failed to decode Protobuf message: TextOrExpr.left: TextExpr.expr: TextOrExpr.left: TextExpr.expr: TextOrExpr.left: TextExpr.expr: TextOrExpr.left: TextExpr.expr: …
```

[proto] re-map decode error

---

Earthfile
topk-py/tests/test_async_collection.py
topk-rs/build.rs

Add explicit build trigger to `topk-rs/build.rs` to make sure crate is rebuilt when any of the proto files change.

[build] add explicit build triggers
